name: UNQUE-PostInscripciones

on:
  push:
    branches:
      - '*'

jobs:
  publish-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew assemble

      - name: Logion
        run: |
          docker build -t app .
          docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrests.DOCKER_HUB_PASSWORD}}
          docker tag app chestersan/proyectoejemplo
          docker push chestersan/proyectoejemplo
