name: UNQUE-PostInscripciones

on:
  push:
    branches:
      - '*'

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [1.8]
    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: ${{matrix.java}}

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew test -i

      - name: Update coverage report in Codacy
        if: success() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev')
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Kotlin --force-language -r build/reports/jacoco/test/jacocoTestReport.xml
  
  linter:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Kotlin Linter (ktlint)
        uses: block42-blockchain-company/ktlint-action@v2.3
        
  publish-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew assemble

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.10.0
        with: 
          username: ${{secrets.DOKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: chestersan/ejemploproyecto
          tags: latest, #{{github.run_number}}
      

  linter2:
    needs: [test,linter]
    runs-on: ubuntu-latest
    steps:
      - name: Kotlin Linter (ktlint)
        uses: block42-blockchain-company/ktlint-action@v2.3


