name: UNQUE-PostInscripciones

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew assemble

      - name: Scripts
        run: docker build -t app .
          
      - name: x
        run: docker login -u chestersan -p ad2cf87b-4a96-4989-8a62-ab650526ff9c
      
      - name: build
        run: docker tag app chestersan/proyectoejemplo
        
      - name: push
        run: docker push chestersan/proyectoejemplo
